app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fados_fullcalendar:
    resource: "@fullCalendarBundle/Resources/config/routing.xml"
sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation