<?php
/**
 * Created by PhpStorm.
 * User: boran
 * Date: 13/09/2017
 * Time: 08:19
 */

namespace AppBundle\Form;

use AppBundle\Entity\Dozent;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\SchuleGroup;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class druckenQueryForm extends AbstractType
{

    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em=$em;
    }


    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $id=$options['id'];
        $standortObj=$this->em->getRepository('AppBundle:StandOrt')->findOneBy(array('id'=>$id));

        $builder->add('SchuleGroup', EntityType::class, [
            'attr' => ['class' => 'form-control selectpicker', 'data-style' => "btn-info"],
            'translation_domain'=>false,
            'placeholder' => '-Wählen Sie bitte eine Gruppe-',
            'class' => SchuleGroup::class,
            'label'=>false,
            'required'=>false,
            'query_builder' => function (EntityRepository $er) use ($standortObj) {
                return $er->createQueryBuilder('SchuleGroup')
                    ->select('SchuleGroup')
                    ->where('SchuleGroup.StandOrt = :standort')
                    ->setParameter('standort', $standortObj)
                    ->orderBy('SchuleGroup.Austritt_Date', 'ASC');
            }
        ])->add('Dozent', EntityType::class, [
            'attr' => ['class' => 'form-control selectpicker', 'data-style' => "btn-info"],
            'translation_domain'=>false,
            'placeholder' => '-Wählen Sie bitte einen Dozenten-',
            'class' => Dozent::class,
            'label'=>false,
            'required'=>false,
            'query_builder' => function (EntityRepository $er) use ($standortObj) {
                return $er->createQueryBuilder('Dozent')
                    ->select('Dozent')
                    ->where('Dozent.Dozent_StandOrt = :standort')
                    ->setParameter('standort', $standortObj)
                    ->orderBy('Dozent.Dozent_Name', 'ASC');
            }
        ])->add('fromDate', DateType::class, [
                'widget' => 'single_text',
                'format' => 'dd.MM.yyyy',
                'attr' => ['placeholder' => 'Von','class' => 'form-control js-datepicker-from'],
                'translation_domain'=>false,
                'html5' => false,
                'label' => false

            ])->add('toDate', DateType::class, [
                'widget' => 'single_text',
                'format' => 'dd.MM.yyyy',
                'attr' => ['placeholder' => 'Bis','class' => 'form-control js-datepicker-to'],
                'translation_domain'=>false,
                'html5' => false,
                'label' => false,
                'placeholder' => 'Datum'
            ])->getForm();
    }

    public function configureOptions(OptionsResolver $resolver)
    {

        $resolver->setDefaults([null,
            'id'=>1
        ]);



        // TODO: Change the autogenerated stub
    }

}