<?php
/**
 * Created by PhpStorm.
 * User: boran
 * Date: 20/08/2017
 * Time: 14:34
 */

namespace AppBundle\Form;

use AppBundle\Entity\SchuleGroup;
use AppBundle\Entity\StandOrt;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ShuhleGroupsFormType extends AbstractType
{
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em=$em;
    }


    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $id=$options['id'];
        $standortObj=$this->em->getRepository('AppBundle:StandOrt')->findOneBy(array('id'=>$id));
        $currentdate = date("Y-m-d");

        $builder->add('schuleGroup',EntityType::class, [
            'attr'=>['class'=>'form-control selectpicker','data-style'=>"btn-info"],
            'translation_domain'=>false,
            'label'=>false,
            'placeholder' => '-Suchen Sie Die Gruppe aus-',
            'class' => SchuleGroup::class,
            'query_builder' => function(EntityRepository $er)use ($standortObj,$currentdate) {
                return $er->createQueryBuilder('SchuleGroup')
                    ->select("SchuleGroup")
                    ->where('SchuleGroup.StandOrt = :standort AND SchuleGroup.Austritt_Date > :currentdate')
                    ->setParameter('standort',$standortObj )
                    ->setParameter('currentdate',$currentdate )
                    ->orderBy('SchuleGroup.Austritt_Date', 'ASC');
            }
        ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {

        $resolver->setDefaults([null,
            'id'=>1
        ]);



        // TODO: Change the autogenerated stub
    }

}